all :
	#Python does not need to compile but gradescope requires something here
	#So we just output a placeholder message to the terminal
	echo "Python does not need to compile!"

	# running drainage.py

	
run :
	python3 drainage.py
