all :
	#Python does not need to compile but gradescope requires something here
	#So we just output a placeholder message to the terminal
	echo "Python does not need to compile!"

	# running daycare.py

	
run :
	python3 daycare.py
